# database 연동 설정
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    각자 PC에 만들어놓은 Database이름을 써야 합니다.
    url: jdbc:mysql://freshmancommunity.cjieyc0k4yq1.ap-northeast-2.rds.amazonaws.com:3306/freshmandb
    #    mysql에 생성한 사용자 계정 정보를 써야 합니다.
    username: admin
    password: freshman1234
  thymeleaf:
    cache: false


  # spring data jpa 설정
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
