spring:
  # H2 Database ??
  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:tcp://localhost/~/freshman   # H2 DB ?? ?? (In-Memory Mode)
#    username: sa
    #url: 'jdbc:h2:~/test'    # H2 DB ?? ?? (Embedded Mode)
  #    username: username        # H2 DB ?? ID (??? ??)
  #    password: password        # H2 DB ?? PW (??? ??)
    url: jdbc:mysql://freshmancommunity.cjieyc0k4yq1.ap-northeast-2.rds.amazonaws.com:3306/freshmandb
    username: admin
    password: freshman1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev

  # H2 Console ??
  h2:
    console: # H2 DB? ??? ??? ? ?? ??
      enabled: true           # H2 Console ?? ??
      path: /h2-console       # H2 Console ?? ??

  # JPA ??
  jpa:
    hibernate:
      ddl-auto: update        # DB ??? ?? (none, create, create-drop, update, validate)
    properties:
      hibernate:
        format_sql: true      # ?? ?? ?? (??)
        show_sql: true        # ?? ?? ??
    database: mysql